export const COPY = {
  "zh-CN": {
    htmlLang: "zh-Hans",
    metaTitle: "蔡倪 Bobby — 个人主页",
    nameDisplay: "蔡倪（Bobby CAI Ni）",
    jobTitle: "助理 IT 开发经理 · 大数据技术专家",
    showContacts: "显示联系方式",
    contactEmail: "电子邮箱",
    contactPhone: "电话",
    contactLocation: "所在地",
    contactAddress: "中国香港",
    navAbout: "关于",
    navResume: "履历",
    navPortfolio: "作品",
    navBlog: "随笔",
    navContact: "联系",
    langToggle: "繁體",
    themeToggle: "主题",
    /* About */
    aboutTitle: "关于我",
    aboutP1: "我是蔡倪（Bobby CAI Ni），现任中国移动香港公司信息技术中心-中台运营支撑的助理 IT 开发经理及大数据技术专家。",
    aboutP2: "我的核心职责是主导大数据应用的整体规划与落地，推动 AI 与大数据技术在客户洞察、精准营销、风险控制等核心业务场景中的应用，以提升自助化分析能力。同时，我负责统筹各部门数据需求的全生命周期管理，与业务部门协同开展关键业务领域的数据专题分析，将分析结果转化为自动化的多源数据融合报告，为管理层及业务部门提供数据驱动的决策支持。此外，我还致力于构建安全可控的数据生态合作模式，推动数据能力的产品化封装与商业化输出。",
    aboutP3: "在技术技能方面，我精通全栈开发，涵盖前端（HTML、JavaScript、CSS、C#）、后端（Java、Node.js、Python）及数据应用开发（Hive、Spark、PL/SQL、MongoDB），并具备移动端（iOS、Android）以及 Shell、AI-Python 等开发能力。",
    aboutP4: "我持有多项权威认证，包括 AWS 机器学习专家级认证、AWS 解决方案架构师认证、PMP 项目管理认证、CKA 认证、CDMP 数据管理认证、中国移动梧桐大数据助理级技能认证以及中国移动中级 AI 人才培训认证（技术方向），并入选集团 IT 专家人才库。",
    aboutP5: "在工作中，我始终坚持「技术驱动业务」，例如首创引入 AI 大模型优化数据治理流程，解决了地址数据标准化难题，有效支撑了精准营销策略的落地。",
    /* Services */
    serviceTitle: "专业领域",
    services: [
      { title: "大数据与人工智能", desc: "规划并落地大数据应用，推动 AI 与大数据在客户洞察、精准营销、风控等场景的价值闭环。" },
      { title: "全栈与工程化",    desc: "覆盖前端、后端、数据应用与移动端工程实践，支撑中台与业务系统建设。" },
      { title: "数据工程与自助分析", desc: "统筹数据需求全生命周期，开展专题分析并沉淀自动化、多源融合的分析报告能力。" },
      { title: "数据治理与生态合作", desc: "构建安全可控的数据合作模式，推动数据能力产品化封装与商业化输出。" },
    ],
    /* Highlights */
    highlightsTitle: "工作亮点",
    highlights: [
      { name: "数据治理创新", text: "率先引入 AI 大模型优化数据治理流程，解决地址数据标准化难题，支撑精准营销落地。", avatar: "/avatar-1.png" },
      { name: "业务赋能",     text: "将分析结果转化为自动化多源数据融合报告，为管理层与业务部门提供数据驱动的决策支持。", avatar: "/avatar-2.png" },
    ],
    partnersTitle: "合作伙伴",
    /* Resume */
    resumeTitle: "履历",
    certsTitle: "专业认证",
    certsItemTitle: "权威认证与人才资质",
    certsSpan: "持续更新",
    certsText: "AWS 机器学习专家级认证、AWS 解决方案架构师认证、PMP、CKA、CDMP、中国移动梧桐大数据助理级技能认证、中国移动中级 AI 人才培训认证（技术方向）；入选集团 IT 专家人才库。",
    expTitle: "职业经历",
    expItemTitle: "中国移动香港有限公司",
    expSpan: "至今",
    expText: "信息技术中心 · 中台运营支撑。任助理 IT 开发经理及大数据技术专家，主导大数据应用规划与落地，推动 AI 与大数据在核心业务场景的应用，统筹数据需求管理与跨部门数据专题分析。",
    skillsTitle: "技能侧重",
    skills: [
      { name: "大数据（Spark / Hive）", pct: 88 },
      { name: "Java / 后端工程",       pct: 82 },
      { name: "Python / AI 与脚本",    pct: 85 },
      { name: "前端与全栈交付",         pct: 78 },
    ],
    /* Portfolio */
    portfolioTitle: "作品展示",
    filterAll: "全部",
    filterWebDesign: "数据可视化",
    filterApps: "平台与工具",
    filterWebDev: "工程实践",
    selectCategory: "选择分类",
    catLabels: { "web design": "数据可视化", applications: "平台与工具", "web development": "工程实践" },
    projects: [
      { title: "Finance",     cat: "web development", img: "/project-1.jpg" },
      { title: "Orizon",      cat: "web development", img: "/project-2.png" },
      { title: "Fundo",       cat: "web design",      img: "/project-3.jpg" },
      { title: "Brawlhalla",  cat: "applications",    img: "/project-4.png" },
      { title: "DSM.",        cat: "web design",      img: "/project-5.png" },
      { title: "MetaSpark",   cat: "web design",      img: "/project-6.png" },
      { title: "Summary",     cat: "web development", img: "/project-7.png" },
      { title: "Task Manager",cat: "applications",    img: "/project-8.jpg" },
      { title: "Arrival",     cat: "web development", img: "/project-9.png" },
    ],
    /* Blog */
    blogTitle: "随笔",
    blogCat: "大数据",
    posts: [
      { title: "自助分析与数据产品化思考", excerpt: "从需求统筹到报告自动化，如何把分析能力沉淀为可复用的数据产品。", date: "2024-06", dateTime: "2024-06-01", img: "/blog-1.jpg" },
      { title: "AI 在数据治理中的实践",   excerpt: "以大模型辅助标准化与质量提升为例，讨论技术与业务的结合点。",       date: "2024-08", dateTime: "2024-08-15", img: "/blog-2.jpg" },
      { title: "精准营销背后的数据链路",  excerpt: "客户洞察、特征工程与策略闭环中的关键能力与实践要点。",             date: "2024-11", dateTime: "2024-11-20", img: "/blog-3.jpg" },
    ],
    /* Contact */
    contactTitle: "联系",
    formTitle: "留言",
    phName: "姓名",
    phEmail: "电子邮箱",
    phMsg: "留言内容",
    sendBtn: "发送",
    mapTitle: "中国香港",
  },
  "zh-TW": {
    htmlLang: "zh-Hant",
    metaTitle: "蔡倪 Bobby — 個人主頁",
    nameDisplay: "蔡倪（Bobby CAI Ni）",
    jobTitle: "助理 IT 開發經理 · 大數據技術專家",
    showContacts: "顯示聯絡方式",
    contactEmail: "電子郵件",
    contactPhone: "電話",
    contactLocation: "所在地",
    contactAddress: "中國香港",
    navAbout: "關於",
    navResume: "履歷",
    navPortfolio: "作品",
    navBlog: "隨筆",
    navContact: "聯絡",
    langToggle: "简体",
    themeToggle: "主題",
    aboutTitle: "關於我",
    aboutP1: "我是蔡倪（Bobby CAI Ni），現任中國移動香港公司信息技術中心-中台運營支援的助理 IT 開發經理及大數據技術專家。",
    aboutP2: "我的核心職責是主導大數據應用的整體規劃與落地，推動 AI 與大數據技術在客戶洞察、精準營銷、風險控制等核心業務場景中的應用，以提升自助化分析能力。同時，我負責統籌各部門數據需求的全生命週期管理，與業務部門協同開展關鍵業務領域的數據專題分析，將分析結果轉化為自動化的多源數據融合報告，為管理層及業務部門提供數據驅動的決策支持。此外，我還致力於構建安全可控的數據生態合作模式，推動數據能力的產品化封裝與商業化輸出。",
    aboutP3: "在技術技能方面，我精通全端開發，涵蓋前端（HTML、JavaScript、CSS、C#）、後端（Java、Node.js、Python）及數據應用開發（Hive、Spark、PL/SQL、MongoDB），並具備移動端（iOS、Android）以及 Shell、AI-Python 等開發能力。",
    aboutP4: "我持有多項權威認證，包括 AWS 機器學習專家級認證、AWS 解決方案架構師認證、PMP 項目管理認證、CKA 認證、CDMP 數據管理認證、中國移動梧桐大數據助理級技能認證以及中國移動中級 AI 人才培訓認證（技術方向），並入選集團 IT 專家人才庫。",
    aboutP5: "在工作中，我始終堅持「技術驅動業務」，例如首創引入 AI 大模型優化數據治理流程，解決了地址數據標準化難題，有效支撐了精準營銷策略的落地。",
    serviceTitle: "專業領域",
    services: [
      { title: "大數據與人工智能",   desc: "規劃並落地大數據應用，推動 AI 與大數據在客戶洞察、精準營銷、風控等場景的價值閉環。" },
      { title: "全端與工程化",       desc: "涵蓋前端、後端、數據應用與移動端工程實踐，支撐中台與業務系統建設。" },
      { title: "數據工程與自助分析", desc: "統籌數據需求全生命週期，開展專題分析並沉澱自動化、多源融合的分析報告能力。" },
      { title: "數據治理與生態合作", desc: "構建安全可控的數據合作模式，推動數據能力產品化封裝與商業化輸出。" },
    ],
    highlightsTitle: "工作亮點",
    highlights: [
      { name: "數據治理創新", text: "率先引入 AI 大模型優化數據治理流程，解決地址數據標準化難題，支撐精準營銷落地。", avatar: "/avatar-1.png" },
      { name: "業務賦能",     text: "將分析結果轉化為自動化多源數據融合報告，為管理層與業務部門提供數據驅動的決策支持。", avatar: "/avatar-2.png" },
    ],
    partnersTitle: "合作夥伴",
    resumeTitle: "履歷",
    certsTitle: "專業認證",
    certsItemTitle: "權威認證與人才資質",
    certsSpan: "持續更新",
    certsText: "AWS 機器學習專家級認證、AWS 解決方案架構師認證、PMP、CKA、CDMP、中國移動梧桐大數據助理級技能認證、中國移動中級 AI 人才培訓認證（技術方向）；入選集團 IT 專家人才庫。",
    expTitle: "職業經歷",
    expItemTitle: "中國移動香港有限公司",
    expSpan: "至今",
    expText: "信息技術中心 · 中台運營支援。任助理 IT 開發經理及大數據技術專家，主導大數據應用規劃與落地，推動 AI 與大數據在核心業務場景的應用，統籌數據需求管理與跨部門數據專題分析。",
    skillsTitle: "技能側重",
    skills: [
      { name: "大數據（Spark / Hive）", pct: 88 },
      { name: "Java / 後端工程",        pct: 82 },
      { name: "Python / AI 與腳本",     pct: 85 },
      { name: "前端與全端交付",          pct: 78 },
    ],
    portfolioTitle: "作品展示",
    filterAll: "全部",
    filterWebDesign: "數據可視化",
    filterApps: "平台與工具",
    filterWebDev: "工程實踐",
    selectCategory: "選擇分類",
    catLabels: { "web design": "數據可視化", applications: "平台與工具", "web development": "工程實踐" },
    projects: [
      { title: "Finance",     cat: "web development", img: "/project-1.jpg" },
      { title: "Orizon",      cat: "web development", img: "/project-2.png" },
      { title: "Fundo",       cat: "web design",      img: "/project-3.jpg" },
      { title: "Brawlhalla",  cat: "applications",    img: "/project-4.png" },
      { title: "DSM.",        cat: "web design",      img: "/project-5.png" },
      { title: "MetaSpark",   cat: "web design",      img: "/project-6.png" },
      { title: "Summary",     cat: "web development", img: "/project-7.png" },
      { title: "Task Manager",cat: "applications",    img: "/project-8.jpg" },
      { title: "Arrival",     cat: "web development", img: "/project-9.png" },
    ],
    blogTitle: "隨筆",
    blogCat: "大數據",
    posts: [
      { title: "自助分析與數據產品化思考", excerpt: "從需求統籌到報告自動化，如何把分析能力沉澱為可複用的數據產品。",  date: "2024-06", dateTime: "2024-06-01", img: "/blog-1.jpg" },
      { title: "AI 在數據治理中的實踐",   excerpt: "以大模型輔助標準化與質量提升為例，討論技術與業務的結合點。",    date: "2024-08", dateTime: "2024-08-15", img: "/blog-2.jpg" },
      { title: "精準營銷背後的數據鏈路",  excerpt: "客戶洞察、特徵工程與策略閉環中的關鍵能力與實踐要點。",          date: "2024-11", dateTime: "2024-11-20", img: "/blog-3.jpg" },
    ],
    contactTitle: "聯絡",
    formTitle: "留言",
    phName: "姓名",
    phEmail: "電子郵件",
    phMsg: "留言內容",
    sendBtn: "發送",
    mapTitle: "中國香港",
  },
};
