export const ZH_TW = {
  htmlLang: "zh-Hant",
  metaTitle: "蔡倪 Bobby — 個人主頁",
  nameDisplay: "蔡倪（Bobby CAI Ni）",
  jobTitle: "助理 IT 開發經理 · 大數據技術專家",
  showContacts: "顯示聯絡方式",
  contactEmail: "電子郵件",
  contactPhone: "電話",
  contactLocation: "所在地",
  contactAddress: "中國香港",
  navAbout: "關於",
  navResume: "履歷",
  navPortfolio: "作品",
  navBlog: "隨筆",
  langToggle: "简体",
  themeToggle: "主題",
  aboutTitle: "關於我",
  aboutP1:
    "我是蔡倪（Bobby CAI Ni），現任中國移動香港公司信息技術中心-中台運營支援的助理 IT 開發經理及大數據技術專家。",
  aboutP2:
    "我的核心職責是主導大數據應用的整體規劃與落地，推動 AI 與大數據技術在客戶洞察、精準營銷、風險控制等核心業務場景中的應用，以提升自助化分析能力。同時，我負責統籌各部門數據需求的全生命週期管理，與業務部門協同開展關鍵業務領域的數據專題分析，將分析結果轉化為自動化的多源數據融合報告，為管理層及業務部門提供數據驅動的決策支持。此外，我還致力於構建安全可控的數據生態合作模式，推動數據能力的產品化封裝與商業化輸出。",
  aboutP5:
    "在工作中，我始終堅持「技術驅動業務」，例如首創引入 AI 大模型優化數據治理流程，解決了地址數據標準化難題，有效支撐了精準營銷策略的落地。",
  serviceTitle: "專業領域",
  services: [
    {
      title: "大數據與人工智能",
      desc: "規劃並落地大數據應用，推動 AI 與大數據在客戶洞察、精準營銷、風控等場景的價值閉環。",
    },
    { title: "全端與工程化", desc: "涵蓋前端、後端、數據應用與移動端工程實踐，支撐中台與業務系統建設。" },
    {
      title: "數據工程與自助分析",
      desc: "統籌數據需求全生命週期，開展專題分析並沉澱自動化、多源融合的分析報告能力。",
    },
    { title: "數據治理與生態合作", desc: "構建安全可控的數據合作模式，推動數據能力產品化封裝與商業化輸出。" },
  ],
  highlightsTitle: "工作亮點",
  highlights: [
    {
      name: "數據治理創新",
      text: "率先引入 AI 大模型優化數據治理流程，解決地址數據標準化難題，支撐精準營銷落地。",
      icon: "governance",
    },
    {
      name: "業務賦能",
      text: "將分析結果轉化為自動化多源數據融合報告，為管理層與業務部門提供數據驅動的決策支持。",
      icon: "impact",
    },
  ],
  certShowcaseTitle: "證書展示",
  certShowcase: [
    "AWS 機器學習專家級認證（MLS）",
    "AWS 解決方案架構師認證（SAA）",
    "PMP 專案管理認證",
    "CKA 認證",
    "CDMP 數據管理認證",
    "中國移動梧桐大數據助理級技能認證",
    "中國移動中級 AI 人才培訓認證（技術方向）",
  ],
  resumeTitle: "履歷",
  certsTitle: "專業認證",
  certsItemTitle: "權威認證與人才資質",
  certsSpan: "持續更新",
  certsText:
    "AWS 機器學習專家級認證、AWS 解決方案架構師認證、PMP、CKA、CDMP、中國移動梧桐大數據助理級技能認證、中國移動中級 AI 人才培訓認證（技術方向）；入選集團 IT 專家人才庫。",
  expTitle: "職業經歷",
  expItemTitle: "中國移動香港有限公司",
  expSpan: "至今",
  expText:
    "信息技術中心 · 中台運營支援。任助理 IT 開發經理及大數據技術專家，主導大數據應用規劃與落地，推動 AI 與大數據在核心業務場景的應用，統籌數據需求管理與跨部門數據專題分析。",
  skillsTitle: "技能側重",
  skills: [
    { name: "大數據（Spark / Hive）", pct: 88 },
    { name: "Java / 後端工程", pct: 82 },
    { name: "Python / AI 與腳本", pct: 85 },
    { name: "前端與全端交付", pct: 78 },
  ],
  portfolioTitle: "作品展示",
  filterAll: "全部",
  filterWebDesign: "數據可視化",
  filterApps: "平台與工具",
  filterWebDev: "工程實踐",
  selectCategory: "選擇分類",
  catLabels: { "web design": "數據可視化", applications: "平台與工具", "web development": "工程實踐" },
  projects: [
    { title: "Finance", cat: "web development", img: "/project-1.jpg" },
    { title: "Orizon", cat: "web development", img: "/project-2.png" },
    { title: "Fundo", cat: "web design", img: "/project-3.jpg" },
    { title: "Brawlhalla", cat: "applications", img: "/project-4.png" },
    { title: "DSM.", cat: "web design", img: "/project-5.png" },
    { title: "MetaSpark", cat: "web design", img: "/project-6.png" },
    { title: "Summary", cat: "web development", img: "/project-7.png" },
    { title: "Task Manager", cat: "applications", img: "/project-8.jpg" },
    { title: "Arrival", cat: "web development", img: "/project-9.png" },
  ],
  blogTitle: "隨筆",
  blogCat: "大數據",
  posts: [
    {
      title: "自助分析與數據產品化思考",
      excerpt: "從需求統籌到報告自動化，如何把分析能力沉澱為可複用的數據產品。",
      date: "2024-06",
      dateTime: "2024-06-01",
      img: "/blog-1.jpg",
    },
    {
      title: "AI 在數據治理中的實踐",
      excerpt: "以大模型輔助標準化與質量提升為例，討論技術與業務的結合點。",
      date: "2024-08",
      dateTime: "2024-08-15",
      img: "/blog-2.jpg",
    },
    {
      title: "精準營銷背後的數據鏈路",
      excerpt: "客戶洞察、特徵工程與策略閉環中的關鍵能力與實踐要點。",
      date: "2024-11",
      dateTime: "2024-11-20",
      img: "/blog-3.jpg",
    },
  ],
};

